name: "Image Push"

on:
  push:
    branches:
    - main
  workflow_dispatch:

env:
  ARTIFACT_REGISTRY: stego-docker-prd
  REGION: asia-northeast1
  APP_NAME: web

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: 'Google auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: '${{secrets.WIF_PROVIDER}}'
          service_account: '${{secrets.WIF_SERVICE_ACCOUNT}}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 379.0.0'

      - name: 'Docker auth'
        run: |-
          gcloud auth configure-docker ${{env.REGION}}-docker.pkg.dev

      - name: 'Build and push container'
        run: |-
          touch .env
          echo "NEXT_PUBLIC_PROD_AUTH_API_KEY=${{secrets.NEXT_PUBLIC_PROD_AUTH_API_KEY}}" >> .env
          echo "NEXT_PUBLIC_PROD_AUTH_DOMAIN=${{secrets.NEXT_PUBLIC_PROD_AUTH_DOMAIN}}" >> .env
          echo "NEXT_PUBLIC_PROD_API_BASE_URL=${{secrets.NEXT_PUBLIC_PROD_API_BASE_URL}}" >> .env
          echo "NEXT_PUBLIC_PROD_WS_BASE_URL=${{secrets.NEXT_PUBLIC_PROD_WS_BASE_URL}}" >> .env
          docker build -t "${{env.REGION}}-docker.pkg.dev/${{secrets.PROJECT_ID}}/${{env.ARTIFACT_REGISTRY}}/${{env.APP_NAME}}:${{github.sha}}" .
          docker push "${{env.REGION}}-docker.pkg.dev/${{secrets.PROJECT_ID}}/${{env.ARTIFACT_REGISTRY}}/${{env.APP_NAME}}:${{github.sha}}"

      - name: Checkout stego-ops repository
        uses: actions/checkout@v2
        with:
          repository: 'yamato0211/stego-ops'
          ref: 'main'
          token: ${{ secrets.PAT }}
          path: 'stego-ops'

      - name: Update image tag in deployment.yaml
        run: |
          yq e -i '.spec.template.spec.containers[0].image = "${{env.REGION}}-docker.pkg.dev/${{secrets.PROJECT_ID}}/${{env.ARTIFACT_REGISTRY}}/${{env.APP_NAME}}:${{github.sha}}"' stego-ops/kubernetes/web/deployment.yaml

      - name: Commit and push changes
        run: |
          cd stego-ops
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add kubernetes/web/deployment.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push
